### PR TITLE
Add a patch to run gnarl on boards without OLED module

### PR DESCRIPTION
**Pull request by trixing**
In particular [this module](https://www.banggood.com/LILYGO-2Pcs-TTGO-ESP32-SX1276-LoRa-868MHz-bluetooth-WI-FI-Lora-Internet-Antenna-Development-Board-p-1295045.html)

Otherwise it will hang randomly.

### CODE REVIEW

**Comment by trixing** [comment]
I have updated this to the latest master. Seems to work even better now with Loop & Medtronic pump.

**Comment by ecc1** [comment]
I would prefer an approach that uses OLED_ENABLE in the lib/oled library code, rather than in the gnarl "application code" -- that way the other applications would also work without a display. Basically an #ifdef around all of oled.c, with dummy definitions of all the functions in the #else branch.

**Comment by trixing** [comment]
Like this?

**Comment by ecc1** [comment]
Applied to dev branch, thanks.

**Pull request closed without merging**
